{"url": "https://api.github.com/repos/tensorflow/tensorflow/issues/comments/321930910", "html_url": "https://github.com/tensorflow/tensorflow/issues/6602#issuecomment-321930910", "issue_url": "https://api.github.com/repos/tensorflow/tensorflow/issues/6602", "id": 321930910, "node_id": "MDEyOklzc3VlQ29tbWVudDMyMTkzMDkxMA==", "user": {"login": "nikste", "id": 11996097, "node_id": "MDQ6VXNlcjExOTk2MDk3", "avatar_url": "https://avatars1.githubusercontent.com/u/11996097?v=4", "gravatar_id": "", "url": "https://api.github.com/users/nikste", "html_url": "https://github.com/nikste", "followers_url": "https://api.github.com/users/nikste/followers", "following_url": "https://api.github.com/users/nikste/following{/other_user}", "gists_url": "https://api.github.com/users/nikste/gists{/gist_id}", "starred_url": "https://api.github.com/users/nikste/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/nikste/subscriptions", "organizations_url": "https://api.github.com/users/nikste/orgs", "repos_url": "https://api.github.com/users/nikste/repos", "events_url": "https://api.github.com/users/nikste/events{/privacy}", "received_events_url": "https://api.github.com/users/nikste/received_events", "type": "User", "site_admin": false}, "created_at": "2017-08-11T22:16:45Z", "updated_at": "2017-08-11T22:16:45Z", "author_association": "CONTRIBUTOR", "body_html": "<p>I get the same error with <code>stream_executor.h</code>, when compiling a custom op with <code>nvcc</code> and 1.3.0 binaries:</p>\n<pre><code>In file included from /usr/local/lib/python3.5/dist-packages/tensorflow/include/tensorflow/core/platform/default/stream_executor.h:26:0,\n                 from /usr/local/lib/python3.5/dist-packages/tensorflow/include/tensorflow/core/platform/stream_executor.h:24,\n                 from /usr/local/lib/python3.5/dist-packages/tensorflow/include/tensorflow/core/util/cuda_kernel_helper.h:26,\n                 from roi_align_gpu.cu.cc:8:\n/usr/local/lib/python3.5/dist-packages/tensorflow/include/tensorflow/stream_executor/dso_loader.h:32:30: fatal error: cuda/cuda_config.h: No such file or directory\n</code></pre>", "body_text": "I get the same error with stream_executor.h, when compiling a custom op with nvcc and 1.3.0 binaries:\nIn file included from /usr/local/lib/python3.5/dist-packages/tensorflow/include/tensorflow/core/platform/default/stream_executor.h:26:0,\n                 from /usr/local/lib/python3.5/dist-packages/tensorflow/include/tensorflow/core/platform/stream_executor.h:24,\n                 from /usr/local/lib/python3.5/dist-packages/tensorflow/include/tensorflow/core/util/cuda_kernel_helper.h:26,\n                 from roi_align_gpu.cu.cc:8:\n/usr/local/lib/python3.5/dist-packages/tensorflow/include/tensorflow/stream_executor/dso_loader.h:32:30: fatal error: cuda/cuda_config.h: No such file or directory", "body": "I get the same error with `stream_executor.h`, when compiling a custom op with `nvcc` and 1.3.0 binaries:\r\n```\r\nIn file included from /usr/local/lib/python3.5/dist-packages/tensorflow/include/tensorflow/core/platform/default/stream_executor.h:26:0,\r\n                 from /usr/local/lib/python3.5/dist-packages/tensorflow/include/tensorflow/core/platform/stream_executor.h:24,\r\n                 from /usr/local/lib/python3.5/dist-packages/tensorflow/include/tensorflow/core/util/cuda_kernel_helper.h:26,\r\n                 from roi_align_gpu.cu.cc:8:\r\n/usr/local/lib/python3.5/dist-packages/tensorflow/include/tensorflow/stream_executor/dso_loader.h:32:30: fatal error: cuda/cuda_config.h: No such file or directory\r\n```\r\n\r\n"}