{"url": "https://api.github.com/repos/pytorch/pytorch/issues/comments/319330938", "html_url": "https://github.com/pytorch/pytorch/pull/1583#issuecomment-319330938", "issue_url": "https://api.github.com/repos/pytorch/pytorch/issues/1583", "id": 319330938, "node_id": "MDEyOklzc3VlQ29tbWVudDMxOTMzMDkzOA==", "user": {"login": "1zb", "id": 4254703, "node_id": "MDQ6VXNlcjQyNTQ3MDM=", "avatar_url": "https://avatars3.githubusercontent.com/u/4254703?v=4", "gravatar_id": "", "url": "https://api.github.com/users/1zb", "html_url": "https://github.com/1zb", "followers_url": "https://api.github.com/users/1zb/followers", "following_url": "https://api.github.com/users/1zb/following{/other_user}", "gists_url": "https://api.github.com/users/1zb/gists{/gist_id}", "starred_url": "https://api.github.com/users/1zb/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/1zb/subscriptions", "organizations_url": "https://api.github.com/users/1zb/orgs", "repos_url": "https://api.github.com/users/1zb/repos", "events_url": "https://api.github.com/users/1zb/events{/privacy}", "received_events_url": "https://api.github.com/users/1zb/received_events", "type": "User", "site_admin": false}, "created_at": "2017-08-01T10:20:35Z", "updated_at": "2017-08-01T10:20:51Z", "author_association": "NONE", "body_html": "<p>I can't get these auto-generated functions to work in latest version (0.2.0+8262920).</p>\n<p>The code from <a class=\"issue-link js-issue-link\" data-error-text=\"Failed to load issue title\" data-id=\"201821673\" data-permission-text=\"Issue title is private\" data-url=\"https://github.com/pytorch/pytorch/issues/499\" data-hovercard-type=\"issue\" data-hovercard-url=\"/pytorch/pytorch/issues/499/hovercard\" href=\"https://github.com/pytorch/pytorch/issues/499\">#499</a> will give the error:</p>\n<pre><code>/home/biao/miniconda2/envs/pth/lib/python3.6/site-packages/torch/nn/_functions/thnn/auto.py in forward(ctx, input, *params)\n    152                 args += (None,)\n    153             else:\n--&gt; 154                 raise ValueError(\"missing required argument '%s'\" % param.name)\n    155 \n    156         args += tuple(additional_args)\n\nValueError: missing required argument 'bias'\n</code></pre>\n<p>Any suggesstions?</p>", "body_text": "I can't get these auto-generated functions to work in latest version (0.2.0+8262920).\nThe code from #499 will give the error:\n/home/biao/miniconda2/envs/pth/lib/python3.6/site-packages/torch/nn/_functions/thnn/auto.py in forward(ctx, input, *params)\n    152                 args += (None,)\n    153             else:\n--> 154                 raise ValueError(\"missing required argument '%s'\" % param.name)\n    155 \n    156         args += tuple(additional_args)\n\nValueError: missing required argument 'bias'\n\nAny suggesstions?", "body": "I can't get these auto-generated functions to work in latest version (0.2.0+8262920).\r\n\r\nThe code from #499 will give the error:\r\n```\r\n/home/biao/miniconda2/envs/pth/lib/python3.6/site-packages/torch/nn/_functions/thnn/auto.py in forward(ctx, input, *params)\r\n    152                 args += (None,)\r\n    153             else:\r\n--> 154                 raise ValueError(\"missing required argument '%s'\" % param.name)\r\n    155 \r\n    156         args += tuple(additional_args)\r\n\r\nValueError: missing required argument 'bias'\r\n```\r\n\r\nAny suggesstions?"}