{"url": "https://api.github.com/repos/pytorch/pytorch/issues/10002", "repository_url": "https://api.github.com/repos/pytorch/pytorch", "labels_url": "https://api.github.com/repos/pytorch/pytorch/issues/10002/labels{/name}", "comments_url": "https://api.github.com/repos/pytorch/pytorch/issues/10002/comments", "events_url": "https://api.github.com/repos/pytorch/pytorch/issues/10002/events", "html_url": "https://github.com/pytorch/pytorch/issues/10002", "id": 345646277, "node_id": "MDU6SXNzdWUzNDU2NDYyNzc=", "number": 10002, "title": "Master build / CUDA9.2 for Pascal - No kernel available", "user": {"login": "mfuntowicz", "id": 2241520, "node_id": "MDQ6VXNlcjIyNDE1MjA=", "avatar_url": "https://avatars1.githubusercontent.com/u/2241520?v=4", "gravatar_id": "", "url": "https://api.github.com/users/mfuntowicz", "html_url": "https://github.com/mfuntowicz", "followers_url": "https://api.github.com/users/mfuntowicz/followers", "following_url": "https://api.github.com/users/mfuntowicz/following{/other_user}", "gists_url": "https://api.github.com/users/mfuntowicz/gists{/gist_id}", "starred_url": "https://api.github.com/users/mfuntowicz/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/mfuntowicz/subscriptions", "organizations_url": "https://api.github.com/users/mfuntowicz/orgs", "repos_url": "https://api.github.com/users/mfuntowicz/repos", "events_url": "https://api.github.com/users/mfuntowicz/events{/privacy}", "received_events_url": "https://api.github.com/users/mfuntowicz/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2018-07-30T07:44:01Z", "updated_at": "2018-07-30T08:51:51Z", "closed_at": "2018-07-30T08:51:51Z", "author_association": "NONE", "body_html": "<p>Hi ! I'm experiencing an issue after building Pytorch from the master branch (commit <a class=\"commit-link\" data-hovercard-type=\"commit\" data-hovercard-url=\"https://github.com/pytorch/pytorch/commit/3609977d7f4629f75dd1f8d904ddd5b52388124f/hovercard\" href=\"https://github.com/pytorch/pytorch/commit/3609977d7f4629f75dd1f8d904ddd5b52388124f\"><tt>3609977</tt></a>) targetting P100 GPUs. Everything goes fine during the compilation, and I'm able to import/create tensors etc. Then, we I try to run the training script for my network, I got :</p>\n<pre><code>Multi-GPU setup using devices: [0, 1, 2, 3]\n  0%|                                                         | 0/100000 [00:00&lt;?, ?it/s]THCudaCheck FAIL file=/home/mfuntowi/Workspace/pytorch/aten/src/THC/generic/THCTensorMath.cu line=244 error=48 : no kernel image is available for execution on the device\nTraceback (most recent call last):\n  File \"main.py\", line 179, in &lt;module&gt;\n    for epoch, batch in zip(trg, loader):\n  File \"/home/mfuntowi/miniconda3/envs/pytorch/lib/python3.7/site-packages/torchtext/data/iterator.py\", line 157, in __iter__\n    yield Batch(minibatch, self.dataset, self.device)\n  File \"/home/mfuntowi/miniconda3/envs/pytorch/lib/python3.7/site-packages/torchtext/data/batch.py\", line 27, in __init__\n    setattr(self, name, field.process(batch, device=device))\n  File \"/home/mfuntowi/miniconda3/envs/pytorch/lib/python3.7/site-packages/torchtext/data/field.py\", line 186, in process\n    tensor = self.numericalize(padded, device=device)\n  File \"/home/mfuntowi/miniconda3/envs/pytorch/lib/python3.7/site-packages/torchtext/data/field.py\", line 659, in numericalize\n    padded_batch = torch.stack(numericalized)\nRuntimeError: cuda runtime error (48) : no kernel image is available for execution on the device at /home/mfuntowi/Workspace/pytorch/aten/src/THC/generic/THCTensorMath.cu:244\n</code></pre>\n<p><strong>Build info:</strong></p>\n<ul>\n<li>OS : Centos 7</li>\n<li>gcc : 4.8.5</li>\n<li>cuda : 9.2</li>\n<li>cudnn 7.1.3</li>\n<li>nccl : 2.2.13</li>\n<li>magma : magma-cuda92</li>\n<li>target arch : 6.0 (auto detected)</li>\n</ul>", "body_text": "Hi ! I'm experiencing an issue after building Pytorch from the master branch (commit 3609977) targetting P100 GPUs. Everything goes fine during the compilation, and I'm able to import/create tensors etc. Then, we I try to run the training script for my network, I got :\nMulti-GPU setup using devices: [0, 1, 2, 3]\n  0%|                                                         | 0/100000 [00:00<?, ?it/s]THCudaCheck FAIL file=/home/mfuntowi/Workspace/pytorch/aten/src/THC/generic/THCTensorMath.cu line=244 error=48 : no kernel image is available for execution on the device\nTraceback (most recent call last):\n  File \"main.py\", line 179, in <module>\n    for epoch, batch in zip(trg, loader):\n  File \"/home/mfuntowi/miniconda3/envs/pytorch/lib/python3.7/site-packages/torchtext/data/iterator.py\", line 157, in __iter__\n    yield Batch(minibatch, self.dataset, self.device)\n  File \"/home/mfuntowi/miniconda3/envs/pytorch/lib/python3.7/site-packages/torchtext/data/batch.py\", line 27, in __init__\n    setattr(self, name, field.process(batch, device=device))\n  File \"/home/mfuntowi/miniconda3/envs/pytorch/lib/python3.7/site-packages/torchtext/data/field.py\", line 186, in process\n    tensor = self.numericalize(padded, device=device)\n  File \"/home/mfuntowi/miniconda3/envs/pytorch/lib/python3.7/site-packages/torchtext/data/field.py\", line 659, in numericalize\n    padded_batch = torch.stack(numericalized)\nRuntimeError: cuda runtime error (48) : no kernel image is available for execution on the device at /home/mfuntowi/Workspace/pytorch/aten/src/THC/generic/THCTensorMath.cu:244\n\nBuild info:\n\nOS : Centos 7\ngcc : 4.8.5\ncuda : 9.2\ncudnn 7.1.3\nnccl : 2.2.13\nmagma : magma-cuda92\ntarget arch : 6.0 (auto detected)", "body": "Hi ! I'm experiencing an issue after building Pytorch from the master branch (commit 3609977) targetting P100 GPUs. Everything goes fine during the compilation, and I'm able to import/create tensors etc. Then, we I try to run the training script for my network, I got : \r\n\r\n```\r\nMulti-GPU setup using devices: [0, 1, 2, 3]\r\n  0%|                                                         | 0/100000 [00:00<?, ?it/s]THCudaCheck FAIL file=/home/mfuntowi/Workspace/pytorch/aten/src/THC/generic/THCTensorMath.cu line=244 error=48 : no kernel image is available for execution on the device\r\nTraceback (most recent call last):\r\n  File \"main.py\", line 179, in <module>\r\n    for epoch, batch in zip(trg, loader):\r\n  File \"/home/mfuntowi/miniconda3/envs/pytorch/lib/python3.7/site-packages/torchtext/data/iterator.py\", line 157, in __iter__\r\n    yield Batch(minibatch, self.dataset, self.device)\r\n  File \"/home/mfuntowi/miniconda3/envs/pytorch/lib/python3.7/site-packages/torchtext/data/batch.py\", line 27, in __init__\r\n    setattr(self, name, field.process(batch, device=device))\r\n  File \"/home/mfuntowi/miniconda3/envs/pytorch/lib/python3.7/site-packages/torchtext/data/field.py\", line 186, in process\r\n    tensor = self.numericalize(padded, device=device)\r\n  File \"/home/mfuntowi/miniconda3/envs/pytorch/lib/python3.7/site-packages/torchtext/data/field.py\", line 659, in numericalize\r\n    padded_batch = torch.stack(numericalized)\r\nRuntimeError: cuda runtime error (48) : no kernel image is available for execution on the device at /home/mfuntowi/Workspace/pytorch/aten/src/THC/generic/THCTensorMath.cu:244\r\n```\r\n\r\n**Build info:**\r\n- OS : Centos 7\r\n- gcc : 4.8.5\r\n- cuda : 9.2\r\n- cudnn 7.1.3\r\n- nccl : 2.2.13\r\n- magma : magma-cuda92\r\n- target arch : 6.0 (auto detected)\r\n"}