{"url": "https://api.github.com/repos/pytorch/pytorch/issues/6184", "repository_url": "https://api.github.com/repos/pytorch/pytorch", "labels_url": "https://api.github.com/repos/pytorch/pytorch/issues/6184/labels{/name}", "comments_url": "https://api.github.com/repos/pytorch/pytorch/issues/6184/comments", "events_url": "https://api.github.com/repos/pytorch/pytorch/issues/6184/events", "html_url": "https://github.com/pytorch/pytorch/issues/6184", "id": 310484934, "node_id": "MDU6SXNzdWUzMTA0ODQ5MzQ=", "number": 6184, "title": "load  pretrained vgg11 model error", "user": {"login": "NewRegin", "id": 9006066, "node_id": "MDQ6VXNlcjkwMDYwNjY=", "avatar_url": "https://avatars0.githubusercontent.com/u/9006066?v=4", "gravatar_id": "", "url": "https://api.github.com/users/NewRegin", "html_url": "https://github.com/NewRegin", "followers_url": "https://api.github.com/users/NewRegin/followers", "following_url": "https://api.github.com/users/NewRegin/following{/other_user}", "gists_url": "https://api.github.com/users/NewRegin/gists{/gist_id}", "starred_url": "https://api.github.com/users/NewRegin/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/NewRegin/subscriptions", "organizations_url": "https://api.github.com/users/NewRegin/orgs", "repos_url": "https://api.github.com/users/NewRegin/repos", "events_url": "https://api.github.com/users/NewRegin/events{/privacy}", "received_events_url": "https://api.github.com/users/NewRegin/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2018-04-02T13:29:10Z", "updated_at": "2018-04-04T17:36:57Z", "closed_at": "2018-04-04T17:36:57Z", "author_association": "NONE", "body_html": "<p>env:<br>\n-Pytorch<br>\n-Pytorch version:0.4.0a0+2a4b33b(installed from conda)<br>\n-Python 3.6.4<br>\n-CUDA<br>\n-GPU-Nvidia P100<br>\n-GCC:gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.5)<br>\n-torchvision(installed from master)</p>\n<p>error descripes:<br>\nWhen exec:<br>\nmodels.vgg11(pretrained=True), Then:</p>\n<p>Traceback (most recent call last):<br>\nFile \"\", line 1, in <br>\nFile \"/home/lzh3/anaconda3/lib/python3.6/site-packages/torchvision/models/vgg.py\", line 124, in vgg13<br>\nmodel.load_state_dict(model_zoo.load_url(model_urls['vgg13']))<br>\nFile \"/home/lzh3/anaconda3/lib/python3.6/site-packages/torch/utils/model_zoo.py\", line 66, in load_url<br>\nreturn torch.load(cached_file, map_location=map_location)<br>\nFile \"/home/lzh3/anaconda3/lib/python3.6/site-packages/torch/serialization.py\", line 303, in load<br>\nreturn _load(f, map_location, pickle_module)<br>\nFile \"/home/lzh3/anaconda3/lib/python3.6/site-packages/torch/serialization.py\", line 470, in _load<br>\nresult = unpickler.load()<br>\nFile \"/home/lzh3/anaconda3/lib/python3.6/site-packages/torch/autograd/variable.py\", line 79, in <strong>setstate</strong><br>\nself.requires_grad, _, self._backward_hooks = state<br>\nValueError: too many values to unpack (expected 3)</p>\n<p>I find the len(state) is 4, and state is:<br>\n([0,0...][torch.FloatStorage of size 1728], 0, (64, 3, 3, 3), (27, 9, 3, 1)))</p>", "body_text": "env:\n-Pytorch\n-Pytorch version:0.4.0a0+2a4b33b(installed from conda)\n-Python 3.6.4\n-CUDA\n-GPU-Nvidia P100\n-GCC:gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.5)\n-torchvision(installed from master)\nerror descripes:\nWhen exec:\nmodels.vgg11(pretrained=True), Then:\nTraceback (most recent call last):\nFile \"\", line 1, in \nFile \"/home/lzh3/anaconda3/lib/python3.6/site-packages/torchvision/models/vgg.py\", line 124, in vgg13\nmodel.load_state_dict(model_zoo.load_url(model_urls['vgg13']))\nFile \"/home/lzh3/anaconda3/lib/python3.6/site-packages/torch/utils/model_zoo.py\", line 66, in load_url\nreturn torch.load(cached_file, map_location=map_location)\nFile \"/home/lzh3/anaconda3/lib/python3.6/site-packages/torch/serialization.py\", line 303, in load\nreturn _load(f, map_location, pickle_module)\nFile \"/home/lzh3/anaconda3/lib/python3.6/site-packages/torch/serialization.py\", line 470, in _load\nresult = unpickler.load()\nFile \"/home/lzh3/anaconda3/lib/python3.6/site-packages/torch/autograd/variable.py\", line 79, in setstate\nself.requires_grad, _, self._backward_hooks = state\nValueError: too many values to unpack (expected 3)\nI find the len(state) is 4, and state is:\n([0,0...][torch.FloatStorage of size 1728], 0, (64, 3, 3, 3), (27, 9, 3, 1)))", "body": "env:\r\n-Pytorch\r\n-Pytorch version:0.4.0a0+2a4b33b(installed from conda)\r\n-Python 3.6.4\r\n-CUDA\r\n-GPU-Nvidia P100\r\n-GCC:gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.5)\r\n-torchvision(installed from master)\r\n\r\n\r\nerror descripes:\r\nWhen exec:\r\nmodels.vgg11(pretrained=True), Then:\r\n\r\nTraceback (most recent call last):\r\n  File \"<stdin>\", line 1, in <module>\r\n  File \"/home/lzh3/anaconda3/lib/python3.6/site-packages/torchvision/models/vgg.py\", line 124, in vgg13\r\n    model.load_state_dict(model_zoo.load_url(model_urls['vgg13']))\r\n  File \"/home/lzh3/anaconda3/lib/python3.6/site-packages/torch/utils/model_zoo.py\", line 66, in load_url\r\n    return torch.load(cached_file, map_location=map_location)\r\n  File \"/home/lzh3/anaconda3/lib/python3.6/site-packages/torch/serialization.py\", line 303, in load\r\n    return _load(f, map_location, pickle_module)\r\n  File \"/home/lzh3/anaconda3/lib/python3.6/site-packages/torch/serialization.py\", line 470, in _load\r\n    result = unpickler.load()\r\n  File \"/home/lzh3/anaconda3/lib/python3.6/site-packages/torch/autograd/variable.py\", line 79, in __setstate__\r\n    self.requires_grad, _, self._backward_hooks = state\r\nValueError: too many values to unpack (expected 3)\r\n\r\nI find the len(state) is 4, and state is:\r\n([0,0...][torch.FloatStorage of size 1728], 0, (64, 3, 3, 3), (27, 9, 3, 1)))"}