{"url": "https://api.github.com/repos/tensorflow/tensorflow/issues/comments/292149561", "html_url": "https://github.com/tensorflow/tensorflow/issues/7680#issuecomment-292149561", "issue_url": "https://api.github.com/repos/tensorflow/tensorflow/issues/7680", "id": 292149561, "node_id": "MDEyOklzc3VlQ29tbWVudDI5MjE0OTU2MQ==", "user": {"login": "DfM7", "id": 26778560, "node_id": "MDQ6VXNlcjI2Nzc4NTYw", "avatar_url": "https://avatars3.githubusercontent.com/u/26778560?v=4", "gravatar_id": "", "url": "https://api.github.com/users/DfM7", "html_url": "https://github.com/DfM7", "followers_url": "https://api.github.com/users/DfM7/followers", "following_url": "https://api.github.com/users/DfM7/following{/other_user}", "gists_url": "https://api.github.com/users/DfM7/gists{/gist_id}", "starred_url": "https://api.github.com/users/DfM7/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/DfM7/subscriptions", "organizations_url": "https://api.github.com/users/DfM7/orgs", "repos_url": "https://api.github.com/users/DfM7/repos", "events_url": "https://api.github.com/users/DfM7/events{/privacy}", "received_events_url": "https://api.github.com/users/DfM7/received_events", "type": "User", "site_admin": false}, "created_at": "2017-04-06T11:49:01Z", "updated_at": "2017-04-06T11:49:01Z", "author_association": "NONE", "body_html": "<p><a class=\"user-mention\" data-hovercard-type=\"user\" data-hovercard-url=\"/hovercards?user_id=7946809\" data-octo-click=\"hovercard-link-click\" data-octo-dimensions=\"link_type:self\" href=\"https://github.com/gunan\">@gunan</a> I see, thank you.</p>\n<p>But anyway the solution by <a class=\"user-mention\" data-hovercard-type=\"user\" data-hovercard-url=\"/hovercards?user_id=15782340\" data-octo-click=\"hovercard-link-click\" data-octo-dimensions=\"link_type:self\" href=\"https://github.com/hajome73\">@hajome73</a> doesn't seem to be ideal.<br>\nI took a closer look at the output after applying the solution and it looks suspicious to me. See this gist: <a href=\"https://gist.github.com/trd714/551cd37e00a57a83ae40a36f195b470b\">https://gist.github.com/trd714/551cd37e00a57a83ae40a36f195b470b</a>.<br>\nFirstly, I see two lines that say \"Creating TensorFlow device\" (27 and 32).<br>\nSecondly, I get \"Out of range\" at line 33. After reading the line number 34 I assume that it's somehow related to the CPU as it states _device=\"/job:localhost/replica:0/task:0/cpu:0\". Are lines 33 and 34 an issue at all? If yes, are they related to the initial issue or should I create a new one?</p>\n<p>P.S. I had to wrap the last statement at <a href=\"https://www.tensorflow.org/get_started/get_started#basic_usage\" rel=\"nofollow\">https://www.tensorflow.org/get_started/get_started#basic_usage</a> (estimator.evaluate(input_fn=input_fn)) in a print() function to get the output.</p>", "body_text": "@gunan I see, thank you.\nBut anyway the solution by @hajome73 doesn't seem to be ideal.\nI took a closer look at the output after applying the solution and it looks suspicious to me. See this gist: https://gist.github.com/trd714/551cd37e00a57a83ae40a36f195b470b.\nFirstly, I see two lines that say \"Creating TensorFlow device\" (27 and 32).\nSecondly, I get \"Out of range\" at line 33. After reading the line number 34 I assume that it's somehow related to the CPU as it states _device=\"/job:localhost/replica:0/task:0/cpu:0\". Are lines 33 and 34 an issue at all? If yes, are they related to the initial issue or should I create a new one?\nP.S. I had to wrap the last statement at https://www.tensorflow.org/get_started/get_started#basic_usage (estimator.evaluate(input_fn=input_fn)) in a print() function to get the output.", "body": "@gunan I see, thank you.\r\n\r\nBut anyway the solution by @hajome73 doesn't seem to be ideal.\r\nI took a closer look at the output after applying the solution and it looks suspicious to me. See this gist: https://gist.github.com/trd714/551cd37e00a57a83ae40a36f195b470b.\r\nFirstly, I see two lines that say \"Creating TensorFlow device\" (27 and 32).\r\nSecondly, I get \"Out of range\" at line 33. After reading the line number 34 I assume that it's somehow related to the CPU as it states _device=\"/job:localhost/replica:0/task:0/cpu:0\". Are lines 33 and 34 an issue at all? If yes, are they related to the initial issue or should I create a new one?\r\n\r\nP.S. I had to wrap the last statement at https://www.tensorflow.org/get_started/get_started#basic_usage (estimator.evaluate(input_fn=input_fn)) in a print() function to get the output. \r\n"}