{"url": "https://api.github.com/repos/pytorch/pytorch/issues/7485", "repository_url": "https://api.github.com/repos/pytorch/pytorch", "labels_url": "https://api.github.com/repos/pytorch/pytorch/issues/7485/labels{/name}", "comments_url": "https://api.github.com/repos/pytorch/pytorch/issues/7485/comments", "events_url": "https://api.github.com/repos/pytorch/pytorch/issues/7485/events", "html_url": "https://github.com/pytorch/pytorch/issues/7485", "id": 322098053, "node_id": "MDU6SXNzdWUzMjIwOTgwNTM=", "number": 7485, "title": "Multiprocessing runtime error freeze_support() in Windows 64 bit ", "user": {"login": "banibrata", "id": 7108081, "node_id": "MDQ6VXNlcjcxMDgwODE=", "avatar_url": "https://avatars2.githubusercontent.com/u/7108081?v=4", "gravatar_id": "", "url": "https://api.github.com/users/banibrata", "html_url": "https://github.com/banibrata", "followers_url": "https://api.github.com/users/banibrata/followers", "following_url": "https://api.github.com/users/banibrata/following{/other_user}", "gists_url": "https://api.github.com/users/banibrata/gists{/gist_id}", "starred_url": "https://api.github.com/users/banibrata/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/banibrata/subscriptions", "organizations_url": "https://api.github.com/users/banibrata/orgs", "repos_url": "https://api.github.com/users/banibrata/repos", "events_url": "https://api.github.com/users/banibrata/events{/privacy}", "received_events_url": "https://api.github.com/users/banibrata/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 2, "created_at": "2018-05-10T21:50:36Z", "updated_at": "2018-05-12T06:11:07Z", "closed_at": "2018-05-12T06:09:07Z", "author_association": "NONE", "body_html": "<p>If you have a question or would like help and support, please ask at our<br>\n<a href=\"https://discuss.pytorch.org/\" rel=\"nofollow\">forums</a>.</p>\n<p>If you are submitting a feature request, please preface the title with [feature request].<br>\nIf you are submitting a bug report, please fill in the following details.</p>\n<h2>Issue description</h2>\n<p>When I run the examples of mnist  using python main.py as mentioned in the examples here:<br>\n(<a href=\"https://github.com/pytorch/examples/tree/master/mnist\">https://github.com/pytorch/examples/tree/master/mnist</a>)<br>\ngetting this error:</p>\n<p>Traceback (most recent call last):<br>\nFile \"\", line 1, in <br>\nFile \"C:\\Anaconda\\lib\\multiprocessing\\spawn.py\", line 105, in spawn_main<br>\nexitcode = _main(fd)<br>\nFile \"C:\\Anaconda\\lib\\multiprocessing\\spawn.py\", line 114, in _main<br>\nprepare(preparation_data)<br>\nFile \"C:\\Anaconda\\lib\\multiprocessing\\spawn.py\", line 225, in prepare<br>\n_fixup_main_from_path(data['init_main_from_path'])<br>\nFile \"C:\\Anaconda\\lib\\multiprocessing\\spawn.py\", line 277, in _fixup_main_from_path<br>\nrun_name=\"<strong>mp_main</strong>\")<br>\nFile \"C:\\Anaconda\\lib\\runpy.py\", line 263, in run_path<br>\npkg_name=pkg_name, script_name=fname)<br>\nFile \"C:\\Anaconda\\lib\\runpy.py\", line 96, in _run_module_code<br>\nmod_name, mod_spec, pkg_name, script_name)<br>\nFile \"C:\\Anaconda\\lib\\runpy.py\", line 85, in _run_code<br>\nexec(code, run_globals)<br>\nFile \"C:\\Users\\banide\\notebooks\\examples-master\\mnist\\main.py\", line 106, in <br>\ntrain(epoch)<br>\nFile \"C:\\Users\\banide\\notebooks\\examples-master\\mnist\\main.py\", line 75, in train<br>\nfor batch_idx, (data, target) in enumerate(train_loader):<br>\nFile \"C:\\Anaconda\\lib\\site-packages\\torch\\utils\\data\\dataloader.py\", line 451, in <strong>iter</strong><br>\nreturn _DataLoaderIter(self)<br>\nFile \"C:\\Anaconda\\lib\\site-packages\\torch\\utils\\data\\dataloader.py\", line 239, in <strong>init</strong><br>\nw.start()<br>\nFile \"C:\\Anaconda\\lib\\multiprocessing\\process.py\", line 105, in start<br>\nself._popen = self._Popen(self)<br>\nFile \"C:\\Anaconda\\lib\\multiprocessing\\context.py\", line 223, in _Popen<br>\nreturn _default_context.get_context().Process._Popen(process_obj)<br>\nFile \"C:\\Anaconda\\lib\\multiprocessing\\context.py\", line 322, in _Popen<br>\nreturn Popen(process_obj)<br>\nFile \"C:\\Anaconda\\lib\\multiprocessing\\popen_spawn_win32.py\", line 33, in <strong>init</strong><br>\nprep_data = spawn.get_preparation_data(process_obj._name)<br>\nFile \"C:\\Anaconda\\lib\\multiprocessing\\spawn.py\", line 143, in get_preparation_data<br>\n_check_not_importing_main()<br>\nFile \"C:\\Anaconda\\lib\\multiprocessing\\spawn.py\", line 136, in _check_not_importing_main<br>\nis not going to be frozen to produce an executable.''')<br>\nRuntimeError:<br>\nAn attempt has been made to start a new process before the<br>\ncurrent process has finished its bootstrapping phase.</p>\n<pre><code>    This probably means that you are not using fork to start your\n    child processes and you have forgotten to use the proper idiom\n    in the main module:\n\n        if __name__ == '__main__':\n            freeze_support()\n            ...\n\n    The \"freeze_support()\" line can be omitted if the program\n    is not going to be frozen to produce an executable.\n</code></pre>\n<h2>Code example</h2>\n<p>Please try to provide a minimal example to repro the bug.<br>\nError messages and stack traces are also helpful.</p>\n<h2>System Info</h2>\n<p>Please copy and paste the output from our<br>\n<a href=\"https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py\" rel=\"nofollow\">environment collection script</a><br>\n(or fill out the checklist below manually).</p>\n<p>You can get the script and run it with:</p>\n<pre><code>wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py\n# For security purposes, please check the contents of collect_env.py before running it.\npython collect_env.py\n</code></pre>\n<p>PyTorch version: 0.4.0<br>\nIs debug build: No<br>\nCUDA used to build PyTorch: 9.0</p>\n<p>OS: Microsoft Windows Server 2016 Datacenter<br>\nGCC version: Could not collect<br>\nCMake version: version 3.11.1</p>\n<p>Python version: 3.6<br>\nIs CUDA available: Yes<br>\nCUDA runtime version: 9.0.176<br>\nGPU models and configuration: GPU 0: Tesla K80<br>\nNvidia driver version: 386.07<br>\ncuDNN version: Could not collect</p>\n<p>Versions of relevant libraries:<br>\n[pip3] numpy (1.14.2)<br>\n[pip3] numpydoc (0.7.0)<br>\n[pip3] torch (0.4.0)<br>\n[pip3] torchvision (0.2.1)<br>\n[conda] cuda90                    1.0                           0    pytorch<br>\n[conda] pytorch                   0.4.0           py36_cuda90_cudnn7he774522_1  [cuda90]  pytorch<br>\n[conda] torchvision               0.2.1                     </p>", "body_text": "If you have a question or would like help and support, please ask at our\nforums.\nIf you are submitting a feature request, please preface the title with [feature request].\nIf you are submitting a bug report, please fill in the following details.\nIssue description\nWhen I run the examples of mnist  using python main.py as mentioned in the examples here:\n(https://github.com/pytorch/examples/tree/master/mnist)\ngetting this error:\nTraceback (most recent call last):\nFile \"\", line 1, in \nFile \"C:\\Anaconda\\lib\\multiprocessing\\spawn.py\", line 105, in spawn_main\nexitcode = _main(fd)\nFile \"C:\\Anaconda\\lib\\multiprocessing\\spawn.py\", line 114, in _main\nprepare(preparation_data)\nFile \"C:\\Anaconda\\lib\\multiprocessing\\spawn.py\", line 225, in prepare\n_fixup_main_from_path(data['init_main_from_path'])\nFile \"C:\\Anaconda\\lib\\multiprocessing\\spawn.py\", line 277, in _fixup_main_from_path\nrun_name=\"mp_main\")\nFile \"C:\\Anaconda\\lib\\runpy.py\", line 263, in run_path\npkg_name=pkg_name, script_name=fname)\nFile \"C:\\Anaconda\\lib\\runpy.py\", line 96, in _run_module_code\nmod_name, mod_spec, pkg_name, script_name)\nFile \"C:\\Anaconda\\lib\\runpy.py\", line 85, in _run_code\nexec(code, run_globals)\nFile \"C:\\Users\\banide\\notebooks\\examples-master\\mnist\\main.py\", line 106, in \ntrain(epoch)\nFile \"C:\\Users\\banide\\notebooks\\examples-master\\mnist\\main.py\", line 75, in train\nfor batch_idx, (data, target) in enumerate(train_loader):\nFile \"C:\\Anaconda\\lib\\site-packages\\torch\\utils\\data\\dataloader.py\", line 451, in iter\nreturn _DataLoaderIter(self)\nFile \"C:\\Anaconda\\lib\\site-packages\\torch\\utils\\data\\dataloader.py\", line 239, in init\nw.start()\nFile \"C:\\Anaconda\\lib\\multiprocessing\\process.py\", line 105, in start\nself._popen = self._Popen(self)\nFile \"C:\\Anaconda\\lib\\multiprocessing\\context.py\", line 223, in _Popen\nreturn _default_context.get_context().Process._Popen(process_obj)\nFile \"C:\\Anaconda\\lib\\multiprocessing\\context.py\", line 322, in _Popen\nreturn Popen(process_obj)\nFile \"C:\\Anaconda\\lib\\multiprocessing\\popen_spawn_win32.py\", line 33, in init\nprep_data = spawn.get_preparation_data(process_obj._name)\nFile \"C:\\Anaconda\\lib\\multiprocessing\\spawn.py\", line 143, in get_preparation_data\n_check_not_importing_main()\nFile \"C:\\Anaconda\\lib\\multiprocessing\\spawn.py\", line 136, in _check_not_importing_main\nis not going to be frozen to produce an executable.''')\nRuntimeError:\nAn attempt has been made to start a new process before the\ncurrent process has finished its bootstrapping phase.\n    This probably means that you are not using fork to start your\n    child processes and you have forgotten to use the proper idiom\n    in the main module:\n\n        if __name__ == '__main__':\n            freeze_support()\n            ...\n\n    The \"freeze_support()\" line can be omitted if the program\n    is not going to be frozen to produce an executable.\n\nCode example\nPlease try to provide a minimal example to repro the bug.\nError messages and stack traces are also helpful.\nSystem Info\nPlease copy and paste the output from our\nenvironment collection script\n(or fill out the checklist below manually).\nYou can get the script and run it with:\nwget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py\n# For security purposes, please check the contents of collect_env.py before running it.\npython collect_env.py\n\nPyTorch version: 0.4.0\nIs debug build: No\nCUDA used to build PyTorch: 9.0\nOS: Microsoft Windows Server 2016 Datacenter\nGCC version: Could not collect\nCMake version: version 3.11.1\nPython version: 3.6\nIs CUDA available: Yes\nCUDA runtime version: 9.0.176\nGPU models and configuration: GPU 0: Tesla K80\nNvidia driver version: 386.07\ncuDNN version: Could not collect\nVersions of relevant libraries:\n[pip3] numpy (1.14.2)\n[pip3] numpydoc (0.7.0)\n[pip3] torch (0.4.0)\n[pip3] torchvision (0.2.1)\n[conda] cuda90                    1.0                           0    pytorch\n[conda] pytorch                   0.4.0           py36_cuda90_cudnn7he774522_1  [cuda90]  pytorch\n[conda] torchvision               0.2.1", "body": "If you have a question or would like help and support, please ask at our\r\n[forums](https://discuss.pytorch.org/).\r\n\r\nIf you are submitting a feature request, please preface the title with [feature request].\r\nIf you are submitting a bug report, please fill in the following details.\r\n\r\n## Issue description\r\n\r\nWhen I run the examples of mnist  using python main.py as mentioned in the examples here:\r\n(https://github.com/pytorch/examples/tree/master/mnist)\r\ngetting this error:\r\n\r\nTraceback (most recent call last):\r\n  File \"<string>\", line 1, in <module>\r\n  File \"C:\\Anaconda\\lib\\multiprocessing\\spawn.py\", line 105, in spawn_main\r\n    exitcode = _main(fd)\r\n  File \"C:\\Anaconda\\lib\\multiprocessing\\spawn.py\", line 114, in _main\r\n    prepare(preparation_data)\r\n  File \"C:\\Anaconda\\lib\\multiprocessing\\spawn.py\", line 225, in prepare\r\n    _fixup_main_from_path(data['init_main_from_path'])\r\n  File \"C:\\Anaconda\\lib\\multiprocessing\\spawn.py\", line 277, in _fixup_main_from_path\r\n    run_name=\"__mp_main__\")\r\n  File \"C:\\Anaconda\\lib\\runpy.py\", line 263, in run_path\r\n    pkg_name=pkg_name, script_name=fname)\r\n  File \"C:\\Anaconda\\lib\\runpy.py\", line 96, in _run_module_code\r\n    mod_name, mod_spec, pkg_name, script_name)\r\n  File \"C:\\Anaconda\\lib\\runpy.py\", line 85, in _run_code\r\n    exec(code, run_globals)\r\n  File \"C:\\Users\\banide\\notebooks\\examples-master\\mnist\\main.py\", line 106, in <module>\r\n    train(epoch)\r\n  File \"C:\\Users\\banide\\notebooks\\examples-master\\mnist\\main.py\", line 75, in train\r\n    for batch_idx, (data, target) in enumerate(train_loader):\r\n  File \"C:\\Anaconda\\lib\\site-packages\\torch\\utils\\data\\dataloader.py\", line 451, in __iter__\r\n    return _DataLoaderIter(self)\r\n  File \"C:\\Anaconda\\lib\\site-packages\\torch\\utils\\data\\dataloader.py\", line 239, in __init__\r\n    w.start()\r\n  File \"C:\\Anaconda\\lib\\multiprocessing\\process.py\", line 105, in start\r\n    self._popen = self._Popen(self)\r\n  File \"C:\\Anaconda\\lib\\multiprocessing\\context.py\", line 223, in _Popen\r\n    return _default_context.get_context().Process._Popen(process_obj)\r\n  File \"C:\\Anaconda\\lib\\multiprocessing\\context.py\", line 322, in _Popen\r\n    return Popen(process_obj)\r\n  File \"C:\\Anaconda\\lib\\multiprocessing\\popen_spawn_win32.py\", line 33, in __init__\r\n    prep_data = spawn.get_preparation_data(process_obj._name)\r\n  File \"C:\\Anaconda\\lib\\multiprocessing\\spawn.py\", line 143, in get_preparation_data\r\n    _check_not_importing_main()\r\n  File \"C:\\Anaconda\\lib\\multiprocessing\\spawn.py\", line 136, in _check_not_importing_main\r\n    is not going to be frozen to produce an executable.''')\r\nRuntimeError:\r\n        An attempt has been made to start a new process before the\r\n        current process has finished its bootstrapping phase.\r\n\r\n        This probably means that you are not using fork to start your\r\n        child processes and you have forgotten to use the proper idiom\r\n        in the main module:\r\n\r\n            if __name__ == '__main__':\r\n                freeze_support()\r\n                ...\r\n\r\n        The \"freeze_support()\" line can be omitted if the program\r\n        is not going to be frozen to produce an executable.\r\n\r\n## Code example\r\n\r\nPlease try to provide a minimal example to repro the bug.\r\nError messages and stack traces are also helpful.\r\n\r\n## System Info\r\nPlease copy and paste the output from our\r\n[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)\r\n(or fill out the checklist below manually).\r\n\r\nYou can get the script and run it with:\r\n```\r\nwget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py\r\n# For security purposes, please check the contents of collect_env.py before running it.\r\npython collect_env.py\r\n```\r\n\r\nPyTorch version: 0.4.0\r\nIs debug build: No\r\nCUDA used to build PyTorch: 9.0\r\n\r\nOS: Microsoft Windows Server 2016 Datacenter\r\nGCC version: Could not collect\r\nCMake version: version 3.11.1\r\n\r\nPython version: 3.6\r\nIs CUDA available: Yes\r\nCUDA runtime version: 9.0.176\r\nGPU models and configuration: GPU 0: Tesla K80\r\nNvidia driver version: 386.07\r\ncuDNN version: Could not collect\r\n\r\nVersions of relevant libraries:\r\n[pip3] numpy (1.14.2)\r\n[pip3] numpydoc (0.7.0)\r\n[pip3] torch (0.4.0)\r\n[pip3] torchvision (0.2.1)\r\n[conda] cuda90                    1.0                           0    pytorch\r\n[conda] pytorch                   0.4.0           py36_cuda90_cudnn7he774522_1  [cuda90]  pytorch\r\n[conda] torchvision               0.2.1                     <pip>\r\n\r\n"}