{"url": "https://api.github.com/repos/pytorch/pytorch/issues/comments/386070772", "html_url": "https://github.com/pytorch/pytorch/pull/7185#issuecomment-386070772", "issue_url": "https://api.github.com/repos/pytorch/pytorch/issues/7185", "id": 386070772, "node_id": "MDEyOklzc3VlQ29tbWVudDM4NjA3MDc3Mg==", "user": {"login": "gchanan", "id": 3768583, "node_id": "MDQ6VXNlcjM3Njg1ODM=", "avatar_url": "https://avatars2.githubusercontent.com/u/3768583?v=4", "gravatar_id": "", "url": "https://api.github.com/users/gchanan", "html_url": "https://github.com/gchanan", "followers_url": "https://api.github.com/users/gchanan/followers", "following_url": "https://api.github.com/users/gchanan/following{/other_user}", "gists_url": "https://api.github.com/users/gchanan/gists{/gist_id}", "starred_url": "https://api.github.com/users/gchanan/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/gchanan/subscriptions", "organizations_url": "https://api.github.com/users/gchanan/orgs", "repos_url": "https://api.github.com/users/gchanan/repos", "events_url": "https://api.github.com/users/gchanan/events{/privacy}", "received_events_url": "https://api.github.com/users/gchanan/received_events", "type": "User", "site_admin": false}, "created_at": "2018-05-02T18:12:54Z", "updated_at": "2018-05-02T18:12:54Z", "author_association": "CONTRIBUTOR", "body_html": "<p>This completes <a class=\"issue-link js-issue-link\" data-error-text=\"Failed to load issue title\" data-id=\"318364137\" data-permission-text=\"Issue title is private\" data-url=\"https://github.com/pytorch/pytorch/issues/7034\" data-hovercard-type=\"pull_request\" data-hovercard-url=\"/pytorch/pytorch/pull/7034/hovercard\" href=\"https://github.com/pytorch/pytorch/pull/7034\">#7034</a>; I would argue this should perhaps be a (python) warning rather than an error (see discussion in <a class=\"issue-link js-issue-link\" data-error-text=\"Failed to load issue title\" data-id=\"318364137\" data-permission-text=\"Issue title is private\" data-url=\"https://github.com/pytorch/pytorch/issues/7034\" data-hovercard-type=\"pull_request\" data-hovercard-url=\"/pytorch/pytorch/pull/7034/hovercard\" href=\"https://github.com/pytorch/pytorch/pull/7034\">#7034</a>), but let's make it consistent for now.</p>", "body_text": "This completes #7034; I would argue this should perhaps be a (python) warning rather than an error (see discussion in #7034), but let's make it consistent for now.", "body": "This completes https://github.com/pytorch/pytorch/pull/7034; I would argue this should perhaps be a (python) warning rather than an error (see discussion in https://github.com/pytorch/pytorch/pull/7034), but let's make it consistent for now."}