{"url": "https://api.github.com/repos/tensorflow/tensorflow/issues/comments/232891583", "html_url": "https://github.com/tensorflow/tensorflow/issues/3311#issuecomment-232891583", "issue_url": "https://api.github.com/repos/tensorflow/tensorflow/issues/3311", "id": 232891583, "node_id": "MDEyOklzc3VlQ29tbWVudDIzMjg5MTU4Mw==", "user": {"login": "isabeaups", "id": 12017880, "node_id": "MDQ6VXNlcjEyMDE3ODgw", "avatar_url": "https://avatars2.githubusercontent.com/u/12017880?v=4", "gravatar_id": "", "url": "https://api.github.com/users/isabeaups", "html_url": "https://github.com/isabeaups", "followers_url": "https://api.github.com/users/isabeaups/followers", "following_url": "https://api.github.com/users/isabeaups/following{/other_user}", "gists_url": "https://api.github.com/users/isabeaups/gists{/gist_id}", "starred_url": "https://api.github.com/users/isabeaups/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/isabeaups/subscriptions", "organizations_url": "https://api.github.com/users/isabeaups/orgs", "repos_url": "https://api.github.com/users/isabeaups/repos", "events_url": "https://api.github.com/users/isabeaups/events{/privacy}", "received_events_url": "https://api.github.com/users/isabeaups/received_events", "type": "User", "site_admin": false}, "created_at": "2016-07-15T08:20:23Z", "updated_at": "2016-07-15T08:32:11Z", "author_association": "NONE", "body_html": "<p>Thank you for looking into it.<br>\nI'm seeing this in the PyCharm debugging mode.</p>\n<p>I think you are right, I missidentified the problem. shp is actually ok, the problem occurs while using<br>\n<code>tf.random_normal(shp,mean=0,stddev=1)</code></p>\n<p>This occures inside my _build_graph method of a neural network.</p>\n<p>I have the following line:</p>\n<p><code>xtilde = x + noise_level * tf.random_normal(tf.shape(x), mean=0., stddev=1.)</code></p>\n<p>which fails because<br>\nwhile x.get_shape() = (?,?,1)<br>\ntf.random_normal(tf.shape(x),mean=0,stddev=1).get_shape() = (?,?,?)</p>\n<p>and so the addition fails because the tensors are not of the same shape.</p>\n<p>So the problem is that tensorflow.random_normal has fails to be correctly shaped when the last dimension is 1.</p>", "body_text": "Thank you for looking into it.\nI'm seeing this in the PyCharm debugging mode.\nI think you are right, I missidentified the problem. shp is actually ok, the problem occurs while using\ntf.random_normal(shp,mean=0,stddev=1)\nThis occures inside my _build_graph method of a neural network.\nI have the following line:\nxtilde = x + noise_level * tf.random_normal(tf.shape(x), mean=0., stddev=1.)\nwhich fails because\nwhile x.get_shape() = (?,?,1)\ntf.random_normal(tf.shape(x),mean=0,stddev=1).get_shape() = (?,?,?)\nand so the addition fails because the tensors are not of the same shape.\nSo the problem is that tensorflow.random_normal has fails to be correctly shaped when the last dimension is 1.", "body": "Thank you for looking into it.\nI'm seeing this in the PyCharm debugging mode.\n\nI think you are right, I missidentified the problem. shp is actually ok, the problem occurs while using \n`tf.random_normal(shp,mean=0,stddev=1)`\n\nThis occures inside my _build_graph method of a neural network.\n\nI have the following line:\n\n`xtilde = x + noise_level * tf.random_normal(tf.shape(x),\n                                                                    mean=0.,\n                                                                    stddev=1.)`\n\nwhich fails because\nwhile x.get_shape() = (?,?,1)\ntf.random_normal(tf.shape(x),mean=0,stddev=1).get_shape() = (?,?,?)\n\nand so the addition fails because the tensors are not of the same shape.\n\nSo the problem is that tensorflow.random_normal has fails to be correctly shaped when the last dimension is 1. \n"}