{"url": "https://api.github.com/repos/pytorch/pytorch/issues/comments/404658307", "html_url": "https://github.com/pytorch/pytorch/pull/9345#issuecomment-404658307", "issue_url": "https://api.github.com/repos/pytorch/pytorch/issues/9345", "id": 404658307, "node_id": "MDEyOklzc3VlQ29tbWVudDQwNDY1ODMwNw==", "user": {"login": "vishwakftw", "id": 23639302, "node_id": "MDQ6VXNlcjIzNjM5MzAy", "avatar_url": "https://avatars2.githubusercontent.com/u/23639302?v=4", "gravatar_id": "", "url": "https://api.github.com/users/vishwakftw", "html_url": "https://github.com/vishwakftw", "followers_url": "https://api.github.com/users/vishwakftw/followers", "following_url": "https://api.github.com/users/vishwakftw/following{/other_user}", "gists_url": "https://api.github.com/users/vishwakftw/gists{/gist_id}", "starred_url": "https://api.github.com/users/vishwakftw/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/vishwakftw/subscriptions", "organizations_url": "https://api.github.com/users/vishwakftw/orgs", "repos_url": "https://api.github.com/users/vishwakftw/repos", "events_url": "https://api.github.com/users/vishwakftw/events{/privacy}", "received_events_url": "https://api.github.com/users/vishwakftw/received_events", "type": "User", "site_admin": false}, "created_at": "2018-07-12T21:35:49Z", "updated_at": "2018-07-12T21:35:49Z", "author_association": "CONTRIBUTOR", "body_html": "<pre><code>13:40:52 ======================================================================\n13:40:52 FAIL: test_negative_binomial_log_prob (__main__.TestDistributions)\n13:40:52 ----------------------------------------------------------------------\n13:40:52 Traceback (most recent call last):\n13:40:52   File \"test_distributions.py\", line 918, in test_negative_binomial_log_prob\n13:40:52     self._check_log_prob(NegativeBinomial(total_count, probs), ref_log_prob)\n13:40:52   File \"test_distributions.py\", line 634, in _check_log_prob\n13:40:52     asset_fn(i, val.squeeze(), log_prob)\n13:40:52   File \"test_distributions.py\", line 916, in ref_log_prob\n13:40:52     self.assertAlmostEqual(log_prob, expected, places=3)\n13:40:52   File \"/var/lib/jenkins/workspace/test/common.py\", line 348, in assertAlmostEqual\n13:40:52     self.assertEqual(x, y, prec, msg, allow_inf)\n13:40:52   File \"/var/lib/jenkins/workspace/test/common.py\", line 296, in assertEqual\n13:40:52     self.assertEqual(x.item(), y, prec, message, allow_inf)\n13:40:52   File \"/var/lib/jenkins/workspace/test/common.py\", line 340, in assertEqual\n13:40:52     super(TestCase, self).assertLessEqual(abs(x - y), prec, message)\n13:40:52 AssertionError: 2.9444389791664403 not less than or equal to 0.001\n</code></pre>\n<p>Build failures are legitimate.</p>", "body_text": "13:40:52 ======================================================================\n13:40:52 FAIL: test_negative_binomial_log_prob (__main__.TestDistributions)\n13:40:52 ----------------------------------------------------------------------\n13:40:52 Traceback (most recent call last):\n13:40:52   File \"test_distributions.py\", line 918, in test_negative_binomial_log_prob\n13:40:52     self._check_log_prob(NegativeBinomial(total_count, probs), ref_log_prob)\n13:40:52   File \"test_distributions.py\", line 634, in _check_log_prob\n13:40:52     asset_fn(i, val.squeeze(), log_prob)\n13:40:52   File \"test_distributions.py\", line 916, in ref_log_prob\n13:40:52     self.assertAlmostEqual(log_prob, expected, places=3)\n13:40:52   File \"/var/lib/jenkins/workspace/test/common.py\", line 348, in assertAlmostEqual\n13:40:52     self.assertEqual(x, y, prec, msg, allow_inf)\n13:40:52   File \"/var/lib/jenkins/workspace/test/common.py\", line 296, in assertEqual\n13:40:52     self.assertEqual(x.item(), y, prec, message, allow_inf)\n13:40:52   File \"/var/lib/jenkins/workspace/test/common.py\", line 340, in assertEqual\n13:40:52     super(TestCase, self).assertLessEqual(abs(x - y), prec, message)\n13:40:52 AssertionError: 2.9444389791664403 not less than or equal to 0.001\n\nBuild failures are legitimate.", "body": "```\r\n13:40:52 ======================================================================\r\n13:40:52 FAIL: test_negative_binomial_log_prob (__main__.TestDistributions)\r\n13:40:52 ----------------------------------------------------------------------\r\n13:40:52 Traceback (most recent call last):\r\n13:40:52   File \"test_distributions.py\", line 918, in test_negative_binomial_log_prob\r\n13:40:52     self._check_log_prob(NegativeBinomial(total_count, probs), ref_log_prob)\r\n13:40:52   File \"test_distributions.py\", line 634, in _check_log_prob\r\n13:40:52     asset_fn(i, val.squeeze(), log_prob)\r\n13:40:52   File \"test_distributions.py\", line 916, in ref_log_prob\r\n13:40:52     self.assertAlmostEqual(log_prob, expected, places=3)\r\n13:40:52   File \"/var/lib/jenkins/workspace/test/common.py\", line 348, in assertAlmostEqual\r\n13:40:52     self.assertEqual(x, y, prec, msg, allow_inf)\r\n13:40:52   File \"/var/lib/jenkins/workspace/test/common.py\", line 296, in assertEqual\r\n13:40:52     self.assertEqual(x.item(), y, prec, message, allow_inf)\r\n13:40:52   File \"/var/lib/jenkins/workspace/test/common.py\", line 340, in assertEqual\r\n13:40:52     super(TestCase, self).assertLessEqual(abs(x - y), prec, message)\r\n13:40:52 AssertionError: 2.9444389791664403 not less than or equal to 0.001\r\n```\r\nBuild failures are legitimate."}