{"url": "https://api.github.com/repos/pytorch/pytorch/issues/12719", "repository_url": "https://api.github.com/repos/pytorch/pytorch", "labels_url": "https://api.github.com/repos/pytorch/pytorch/issues/12719/labels{/name}", "comments_url": "https://api.github.com/repos/pytorch/pytorch/issues/12719/comments", "events_url": "https://api.github.com/repos/pytorch/pytorch/issues/12719/events", "html_url": "https://github.com/pytorch/pytorch/issues/12719", "id": 370746941, "node_id": "MDU6SXNzdWUzNzA3NDY5NDE=", "number": 12719, "title": "PyTorch/vision pretrained model inception v3 input transform issue for trace & onnx.", "user": {"login": "BowenBao", "id": 9376104, "node_id": "MDQ6VXNlcjkzNzYxMDQ=", "avatar_url": "https://avatars3.githubusercontent.com/u/9376104?v=4", "gravatar_id": "", "url": "https://api.github.com/users/BowenBao", "html_url": "https://github.com/BowenBao", "followers_url": "https://api.github.com/users/BowenBao/followers", "following_url": "https://api.github.com/users/BowenBao/following{/other_user}", "gists_url": "https://api.github.com/users/BowenBao/gists{/gist_id}", "starred_url": "https://api.github.com/users/BowenBao/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/BowenBao/subscriptions", "organizations_url": "https://api.github.com/users/BowenBao/orgs", "repos_url": "https://api.github.com/users/BowenBao/repos", "events_url": "https://api.github.com/users/BowenBao/events{/privacy}", "received_events_url": "https://api.github.com/users/BowenBao/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 693805995, "node_id": "MDU6TGFiZWw2OTM4MDU5OTU=", "url": "https://api.github.com/repos/pytorch/pytorch/labels/onnx", "name": "onnx", "color": "e99695", "default": false}], "state": "open", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 0, "created_at": "2018-10-16T18:42:52Z", "updated_at": "2018-10-23T16:28:00Z", "closed_at": null, "author_association": "CONTRIBUTOR", "body_html": "<h2><g-emoji class=\"g-emoji\" alias=\"bug\" fallback-src=\"https://assets-cdn.github.com/images/icons/emoji/unicode/1f41b.png\">\ud83d\udc1b</g-emoji> Bug</h2>\n<p>PyTorch/vision pretrained model inception v3 input transform issue for trace &amp; onnx. I have a PR(<a class=\"issue-link js-issue-link\" data-error-text=\"Failed to load issue title\" data-id=\"367981754\" data-permission-text=\"Issue title is private\" data-url=\"https://github.com/pytorch/vision/issues/621\" data-hovercard-type=\"pull_request\" data-hovercard-url=\"/pytorch/vision/pull/621/hovercard\" href=\"https://github.com/pytorch/vision/pull/621\">pytorch/vision#621</a>) for this issue.</p>\n<p>FYI.. This is not captured in CI because inception v3 test is turned off due to precision issue, and pretrained=True is not being tested <a href=\"https://github.com/pytorch/pytorch/blob/master/test/onnx/test_pytorch_onnx_caffe2.py#L393\">https://github.com/pytorch/pytorch/blob/master/test/onnx/test_pytorch_onnx_caffe2.py#L393</a>.</p>\n<h2>To Reproduce</h2>\n<p>Steps to reproduce the behavior:</p>\n<pre><code>dummy_input = torch.Tensor(torch.randn((10, 3, 299, 299))).cuda()\ninception_model = models.inception_v3(pretrained=True).cuda()\ninception_model = inception_model.eval()\ntorch.jit.trace(inception_model, dummy_input)\n&gt;&gt;&gt; TracerWarning: Output nr 1. of the traced function does not match the corresponding output of the Python function. Detailed error:\nNot within tolerance rtol=1e-05 atol=1e-05 at input[0, 735] (3.154785633087158 vs. 0.27894413471221924) and 9999 other locations (100.00%)\n  _check_trace([example_inputs], func, executor_options, module, check_tolerance)\n</code></pre>\n\n<h2>Expected behavior</h2>\n<p>Matching numbers within reasonable precision.</p>\n<h2>Environment</h2>\n<p>PyTorch version: 1.0.0a0+254337f<br>\nIs debug build: No<br>\nCUDA used to build PyTorch: 9.0</p>\n<p>OS: Microsoft Windows 10 Enterprise<br>\nGCC version: Could not collect<br>\nCMake version: version 3.12.2</p>\n<p>Python version: 3.5<br>\nIs CUDA available: Yes<br>\nCUDA runtime version: 9.0.176<br>\nGPU models and configuration: GPU 0: GeForce GTX 1070<br>\nNvidia driver version: 388.13<br>\ncuDNN version: 7.0.5</p>\n<p>Versions of relevant libraries:<br>\n[pip] numpy (1.15.2)<br>\n[pip] torch (1.0.0a0+254337f, d:\\repos\\pytorch)<br>\n[pip] torchvision (0.2.1)<br>\n[conda] 4.5.5</p>\n<h2>Additional context</h2>\n", "body_text": "\ud83d\udc1b Bug\nPyTorch/vision pretrained model inception v3 input transform issue for trace & onnx. I have a PR(pytorch/vision#621) for this issue.\nFYI.. This is not captured in CI because inception v3 test is turned off due to precision issue, and pretrained=True is not being tested https://github.com/pytorch/pytorch/blob/master/test/onnx/test_pytorch_onnx_caffe2.py#L393.\nTo Reproduce\nSteps to reproduce the behavior:\ndummy_input = torch.Tensor(torch.randn((10, 3, 299, 299))).cuda()\ninception_model = models.inception_v3(pretrained=True).cuda()\ninception_model = inception_model.eval()\ntorch.jit.trace(inception_model, dummy_input)\n>>> TracerWarning: Output nr 1. of the traced function does not match the corresponding output of the Python function. Detailed error:\nNot within tolerance rtol=1e-05 atol=1e-05 at input[0, 735] (3.154785633087158 vs. 0.27894413471221924) and 9999 other locations (100.00%)\n  _check_trace([example_inputs], func, executor_options, module, check_tolerance)\n\n\nExpected behavior\nMatching numbers within reasonable precision.\nEnvironment\nPyTorch version: 1.0.0a0+254337f\nIs debug build: No\nCUDA used to build PyTorch: 9.0\nOS: Microsoft Windows 10 Enterprise\nGCC version: Could not collect\nCMake version: version 3.12.2\nPython version: 3.5\nIs CUDA available: Yes\nCUDA runtime version: 9.0.176\nGPU models and configuration: GPU 0: GeForce GTX 1070\nNvidia driver version: 388.13\ncuDNN version: 7.0.5\nVersions of relevant libraries:\n[pip] numpy (1.15.2)\n[pip] torch (1.0.0a0+254337f, d:\\repos\\pytorch)\n[pip] torchvision (0.2.1)\n[conda] 4.5.5\nAdditional context", "body": "## \ud83d\udc1b Bug\r\n\r\nPyTorch/vision pretrained model inception v3 input transform issue for trace & onnx. I have a PR(https://github.com/pytorch/vision/pull/621) for this issue.\r\n\r\nFYI.. This is not captured in CI because inception v3 test is turned off due to precision issue, and pretrained=True is not being tested https://github.com/pytorch/pytorch/blob/master/test/onnx/test_pytorch_onnx_caffe2.py#L393. \r\n\r\n## To Reproduce\r\n\r\nSteps to reproduce the behavior:\r\n\r\n```\r\ndummy_input = torch.Tensor(torch.randn((10, 3, 299, 299))).cuda()\r\ninception_model = models.inception_v3(pretrained=True).cuda()\r\ninception_model = inception_model.eval()\r\ntorch.jit.trace(inception_model, dummy_input)\r\n>>> TracerWarning: Output nr 1. of the traced function does not match the corresponding output of the Python function. Detailed error:\r\nNot within tolerance rtol=1e-05 atol=1e-05 at input[0, 735] (3.154785633087158 vs. 0.27894413471221924) and 9999 other locations (100.00%)\r\n  _check_trace([example_inputs], func, executor_options, module, check_tolerance)\r\n```\r\n\r\n<!-- If you have a code sample, error messages, stack traces, please provide it here as well -->\r\n\r\n## Expected behavior\r\n\r\nMatching numbers within reasonable precision. \r\n\r\n## Environment\r\n\r\nPyTorch version: 1.0.0a0+254337f\r\nIs debug build: No\r\nCUDA used to build PyTorch: 9.0\r\n\r\nOS: Microsoft Windows 10 Enterprise\r\nGCC version: Could not collect\r\nCMake version: version 3.12.2\r\n\r\nPython version: 3.5\r\nIs CUDA available: Yes\r\nCUDA runtime version: 9.0.176\r\nGPU models and configuration: GPU 0: GeForce GTX 1070\r\nNvidia driver version: 388.13\r\ncuDNN version: 7.0.5\r\n\r\nVersions of relevant libraries:\r\n[pip] numpy (1.15.2)\r\n[pip] torch (1.0.0a0+254337f, d:\\repos\\pytorch)\r\n[pip] torchvision (0.2.1)\r\n[conda] 4.5.5\r\n\r\n## Additional context\r\n\r\n<!-- Add any other context about the problem here. -->\r\n"}