{"url": "https://api.github.com/repos/pytorch/pytorch/issues/comments/362159896", "html_url": "https://github.com/pytorch/pytorch/issues/4983#issuecomment-362159896", "issue_url": "https://api.github.com/repos/pytorch/pytorch/issues/4983", "id": 362159896, "node_id": "MDEyOklzc3VlQ29tbWVudDM2MjE1OTg5Ng==", "user": {"login": "yf225", "id": 4063635, "node_id": "MDQ6VXNlcjQwNjM2MzU=", "avatar_url": "https://avatars0.githubusercontent.com/u/4063635?v=4", "gravatar_id": "", "url": "https://api.github.com/users/yf225", "html_url": "https://github.com/yf225", "followers_url": "https://api.github.com/users/yf225/followers", "following_url": "https://api.github.com/users/yf225/following{/other_user}", "gists_url": "https://api.github.com/users/yf225/gists{/gist_id}", "starred_url": "https://api.github.com/users/yf225/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/yf225/subscriptions", "organizations_url": "https://api.github.com/users/yf225/orgs", "repos_url": "https://api.github.com/users/yf225/repos", "events_url": "https://api.github.com/users/yf225/events{/privacy}", "received_events_url": "https://api.github.com/users/yf225/received_events", "type": "User", "site_admin": false}, "created_at": "2018-02-01T05:06:54Z", "updated_at": "2018-02-01T05:06:54Z", "author_association": "CONTRIBUTOR", "body_html": "<p>Yes it's a known issue, <a class=\"user-mention\" data-hovercard-type=\"user\" data-hovercard-url=\"/hovercards?user_id=655866\" data-octo-click=\"hovercard-link-click\" data-octo-dimensions=\"link_type:self\" href=\"https://github.com/colesbury\">@colesbury</a> is looking at it with <a class=\"issue-link js-issue-link\" data-error-text=\"Failed to load issue title\" data-id=\"293381469\" data-permission-text=\"Issue title is private\" data-url=\"https://github.com/pytorch/pytorch/issues/4980\" data-hovercard-type=\"pull_request\" data-hovercard-url=\"/pytorch/pytorch/pull/4980/hovercard\" href=\"https://github.com/pytorch/pytorch/pull/4980\">#4980</a>.</p>", "body_text": "Yes it's a known issue, @colesbury is looking at it with #4980.", "body": "Yes it's a known issue, @colesbury is looking at it with https://github.com/pytorch/pytorch/pull/4980."}