{"url": "https://api.github.com/repos/tensorflow/tensorflow/issues/comments/398174552", "html_url": "https://github.com/tensorflow/tensorflow/pull/19398#issuecomment-398174552", "issue_url": "https://api.github.com/repos/tensorflow/tensorflow/issues/19398", "id": 398174552, "node_id": "MDEyOklzc3VlQ29tbWVudDM5ODE3NDU1Mg==", "user": {"login": "dariocazzani", "id": 13348842, "node_id": "MDQ6VXNlcjEzMzQ4ODQy", "avatar_url": "https://avatars1.githubusercontent.com/u/13348842?v=4", "gravatar_id": "", "url": "https://api.github.com/users/dariocazzani", "html_url": "https://github.com/dariocazzani", "followers_url": "https://api.github.com/users/dariocazzani/followers", "following_url": "https://api.github.com/users/dariocazzani/following{/other_user}", "gists_url": "https://api.github.com/users/dariocazzani/gists{/gist_id}", "starred_url": "https://api.github.com/users/dariocazzani/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/dariocazzani/subscriptions", "organizations_url": "https://api.github.com/users/dariocazzani/orgs", "repos_url": "https://api.github.com/users/dariocazzani/repos", "events_url": "https://api.github.com/users/dariocazzani/events{/privacy}", "received_events_url": "https://api.github.com/users/dariocazzani/received_events", "type": "User", "site_admin": false}, "created_at": "2018-06-18T19:52:42Z", "updated_at": "2018-06-18T19:52:42Z", "author_association": "NONE", "body_html": "<p><a class=\"user-mention\" data-hovercard-type=\"user\" data-hovercard-url=\"/hovercards?user_id=1299636\" data-octo-click=\"hovercard-link-click\" data-octo-dimensions=\"link_type:self\" href=\"https://github.com/case540\">@case540</a><br>\nI need your help with this.<br>\nThe error is</p>\n<div class=\"highlight highlight-source-shell\"><pre>AttributeError: module <span class=\"pl-s\"><span class=\"pl-pds\">'</span>tensorflow.contrib.losses.python.metric_learning<span class=\"pl-pds\">'</span></span> has no attribute <span class=\"pl-s\"><span class=\"pl-pds\">'</span>pairwise_distance_cosine<span class=\"pl-pds\">'</span></span></pre></div>\n<p>But <code>pairwise_distance_cosine</code> is defined in <code>tensorflow.contrib.losses.python.metric_learning</code> (it's the module where I added it)<br>\nI don't understand why <code>MacOS Contrib</code> doesn't fail and <code>Ubuntu contrib</code> does.</p>\n<p>Thanks</p>", "body_text": "@case540\nI need your help with this.\nThe error is\nAttributeError: module 'tensorflow.contrib.losses.python.metric_learning' has no attribute 'pairwise_distance_cosine'\nBut pairwise_distance_cosine is defined in tensorflow.contrib.losses.python.metric_learning (it's the module where I added it)\nI don't understand why MacOS Contrib doesn't fail and Ubuntu contrib does.\nThanks", "body": "@case540 \r\nI need your help with this.\r\nThe error is\r\n```bash\r\nAttributeError: module 'tensorflow.contrib.losses.python.metric_learning' has no attribute 'pairwise_distance_cosine'\r\n```\r\nBut `pairwise_distance_cosine` is defined in `tensorflow.contrib.losses.python.metric_learning` (it's the module where I added it)\r\nI don't understand why `MacOS Contrib` doesn't fail and `Ubuntu contrib` does.\r\n\r\nThanks"}