{"url": "https://api.github.com/repos/tensorflow/tensorflow/issues/23388", "repository_url": "https://api.github.com/repos/tensorflow/tensorflow", "labels_url": "https://api.github.com/repos/tensorflow/tensorflow/issues/23388/labels{/name}", "comments_url": "https://api.github.com/repos/tensorflow/tensorflow/issues/23388/comments", "events_url": "https://api.github.com/repos/tensorflow/tensorflow/issues/23388/events", "html_url": "https://github.com/tensorflow/tensorflow/pull/23388", "id": 375690321, "node_id": "MDExOlB1bGxSZXF1ZXN0MjI3MDc5MDQ1", "number": 23388, "title": "Avoid index out of range in traceable_stack", "user": {"login": "javierluraschi", "id": 3478847, "node_id": "MDQ6VXNlcjM0Nzg4NDc=", "avatar_url": "https://avatars1.githubusercontent.com/u/3478847?v=4", "gravatar_id": "", "url": "https://api.github.com/users/javierluraschi", "html_url": "https://github.com/javierluraschi", "followers_url": "https://api.github.com/users/javierluraschi/followers", "following_url": "https://api.github.com/users/javierluraschi/following{/other_user}", "gists_url": "https://api.github.com/users/javierluraschi/gists{/gist_id}", "starred_url": "https://api.github.com/users/javierluraschi/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/javierluraschi/subscriptions", "organizations_url": "https://api.github.com/users/javierluraschi/orgs", "repos_url": "https://api.github.com/users/javierluraschi/repos", "events_url": "https://api.github.com/users/javierluraschi/events{/privacy}", "received_events_url": "https://api.github.com/users/javierluraschi/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 300136587, "node_id": "MDU6TGFiZWwzMDAxMzY1ODc=", "url": "https://api.github.com/repos/tensorflow/tensorflow/labels/cla:%20yes", "name": "cla: yes", "color": "009800", "default": false}, {"id": 703698475, "node_id": "MDU6TGFiZWw3MDM2OTg0NzU=", "url": "https://api.github.com/repos/tensorflow/tensorflow/labels/kokoro:run", "name": "kokoro:run", "color": "bfdadc", "default": false}, {"id": 987666414, "node_id": "MDU6TGFiZWw5ODc2NjY0MTQ=", "url": "https://api.github.com/repos/tensorflow/tensorflow/labels/ready%20to%20pull", "name": "ready to pull", "color": "2cd643", "default": false}], "state": "closed", "locked": false, "assignee": {"login": "harshini-gadige", "id": 42781361, "node_id": "MDQ6VXNlcjQyNzgxMzYx", "avatar_url": "https://avatars1.githubusercontent.com/u/42781361?v=4", "gravatar_id": "", "url": "https://api.github.com/users/harshini-gadige", "html_url": "https://github.com/harshini-gadige", "followers_url": "https://api.github.com/users/harshini-gadige/followers", "following_url": "https://api.github.com/users/harshini-gadige/following{/other_user}", "gists_url": "https://api.github.com/users/harshini-gadige/gists{/gist_id}", "starred_url": "https://api.github.com/users/harshini-gadige/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/harshini-gadige/subscriptions", "organizations_url": "https://api.github.com/users/harshini-gadige/orgs", "repos_url": "https://api.github.com/users/harshini-gadige/repos", "events_url": "https://api.github.com/users/harshini-gadige/events{/privacy}", "received_events_url": "https://api.github.com/users/harshini-gadige/received_events", "type": "User", "site_admin": false}, "assignees": [{"login": "harshini-gadige", "id": 42781361, "node_id": "MDQ6VXNlcjQyNzgxMzYx", "avatar_url": "https://avatars1.githubusercontent.com/u/42781361?v=4", "gravatar_id": "", "url": "https://api.github.com/users/harshini-gadige", "html_url": "https://github.com/harshini-gadige", "followers_url": "https://api.github.com/users/harshini-gadige/followers", "following_url": "https://api.github.com/users/harshini-gadige/following{/other_user}", "gists_url": "https://api.github.com/users/harshini-gadige/gists{/gist_id}", "starred_url": "https://api.github.com/users/harshini-gadige/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/harshini-gadige/subscriptions", "organizations_url": "https://api.github.com/users/harshini-gadige/orgs", "repos_url": "https://api.github.com/users/harshini-gadige/repos", "events_url": "https://api.github.com/users/harshini-gadige/events{/privacy}", "received_events_url": "https://api.github.com/users/harshini-gadige/received_events", "type": "User", "site_admin": false}], "milestone": null, "comments": 6, "created_at": "2018-10-30T20:58:11Z", "updated_at": "2018-11-02T21:07:40Z", "closed_at": "2018-11-02T21:07:40Z", "author_association": "CONTRIBUTOR", "pull_request": {"url": "https://api.github.com/repos/tensorflow/tensorflow/pulls/23388", "html_url": "https://github.com/tensorflow/tensorflow/pull/23388", "diff_url": "https://github.com/tensorflow/tensorflow/pull/23388.diff", "patch_url": "https://github.com/tensorflow/tensorflow/pull/23388.patch"}, "body_html": "<p>Fix for <a class=\"issue-link js-issue-link\" data-error-text=\"Failed to load issue title\" data-id=\"370128799\" data-permission-text=\"Issue title is private\" data-url=\"https://github.com/rstudio/tensorflow/issues/272\" data-hovercard-type=\"issue\" data-hovercard-url=\"/rstudio/tensorflow/issues/272/hovercard\" href=\"https://github.com/rstudio/tensorflow/issues/272\">rstudio/tensorflow#272</a> which blocks use of devices in TensorFlow 1.11.</p>\n<p>An <code>list index out of range</code> exception triggers in <a href=\"https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/framework/traceable_stack.py#L64\">traceable_stack.py#L64</a> which is initialized in <a href=\"https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/framework/ops.py#L4253\">ops.py#L4253</a> when running from R:</p>\n<pre><code>library(tensorflow)\ndata &lt;- tf$device(\"/cpu:0\")\ncontext &lt;- data$`__enter__`()\n</code></pre>\n<p>The frame records from <code>tf_stack.extract_stack()</code> at <a href=\"https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/framework/ops.py#L4253\">ops.py#L4253</a> looks like:</p>\n<pre><code>&lt;stdin&gt;\n/\u2026/r-tensorflow/lib/python3.6/contextlib.py\n/\u2026/r-tensorflow/lib/python3.6/site-packages/tensorflow/python/framework/ops.py\n</code></pre>\n<p>However, while used from R and other tools that embed Python directly, looks like:</p>\n<pre><code>/\u2026/r-tensorflow/lib/python3.6/contextlib.py\n/\u2026/r-tensorflow/lib/python3.6/site-packages/tensorflow/python/framework/ops.py\n</code></pre>\n<p>Since the Python interpreter is not available when called from R (which embeds Python as a library), <code>&lt;stdin&gt;</code> is missing. One fix is to protect against this be reducing the call stack offset when shorter than expected.</p>\n<p>Please let us know if you have additional feedback or suggestions to get them implemented, thanks!</p>\n<p>Change of behavior originally introduced with <a class=\"commit-link\" data-hovercard-type=\"commit\" data-hovercard-url=\"https://github.com/tensorflow/tensorflow/commit/e5cc33df74ec4f761da26c87bb785edfa3fb8280/hovercard\" href=\"https://github.com/tensorflow/tensorflow/commit/e5cc33df74ec4f761da26c87bb785edfa3fb8280\"><tt>e5cc33d</tt></a>.</p>", "body_text": "Fix for rstudio/tensorflow#272 which blocks use of devices in TensorFlow 1.11.\nAn list index out of range exception triggers in traceable_stack.py#L64 which is initialized in ops.py#L4253 when running from R:\nlibrary(tensorflow)\ndata <- tf$device(\"/cpu:0\")\ncontext <- data$`__enter__`()\n\nThe frame records from tf_stack.extract_stack() at ops.py#L4253 looks like:\n<stdin>\n/\u2026/r-tensorflow/lib/python3.6/contextlib.py\n/\u2026/r-tensorflow/lib/python3.6/site-packages/tensorflow/python/framework/ops.py\n\nHowever, while used from R and other tools that embed Python directly, looks like:\n/\u2026/r-tensorflow/lib/python3.6/contextlib.py\n/\u2026/r-tensorflow/lib/python3.6/site-packages/tensorflow/python/framework/ops.py\n\nSince the Python interpreter is not available when called from R (which embeds Python as a library), <stdin> is missing. One fix is to protect against this be reducing the call stack offset when shorter than expected.\nPlease let us know if you have additional feedback or suggestions to get them implemented, thanks!\nChange of behavior originally introduced with e5cc33d.", "body": "Fix for https://github.com/rstudio/tensorflow/issues/272 which blocks use of devices in TensorFlow 1.11.\r\n\r\nAn `list index out of range` exception triggers in [traceable_stack.py#L64](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/framework/traceable_stack.py#L64) which is initialized in [ops.py#L4253](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/framework/ops.py#L4253) when running from R:\r\n\r\n```\r\nlibrary(tensorflow)\r\ndata <- tf$device(\"/cpu:0\")\r\ncontext <- data$`__enter__`()\r\n```\r\n\r\nThe frame records from `tf_stack.extract_stack()` at [ops.py#L4253](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/framework/ops.py#L4253) looks like:\r\n\r\n```\r\n<stdin>\r\n/\u2026/r-tensorflow/lib/python3.6/contextlib.py\r\n/\u2026/r-tensorflow/lib/python3.6/site-packages/tensorflow/python/framework/ops.py\r\n```\r\n\r\nHowever, while used from R and other tools that embed Python directly, looks like:\r\n\r\n```\r\n/\u2026/r-tensorflow/lib/python3.6/contextlib.py\r\n/\u2026/r-tensorflow/lib/python3.6/site-packages/tensorflow/python/framework/ops.py\r\n```\r\n\r\nSince the Python interpreter is not available when called from R (which embeds Python as a library), `<stdin>` is missing. One fix is to protect against this be reducing the call stack offset when shorter than expected.\r\n\r\nPlease let us know if you have additional feedback or suggestions to get them implemented, thanks!\r\n\r\nChange of behavior originally introduced with https://github.com/tensorflow/tensorflow/commit/e5cc33df74ec4f761da26c87bb785edfa3fb8280."}