{"url": "https://api.github.com/repos/pytorch/pytorch/issues/comments/307409931", "html_url": "https://github.com/pytorch/pytorch/issues/1355#issuecomment-307409931", "issue_url": "https://api.github.com/repos/pytorch/pytorch/issues/1355", "id": 307409931, "node_id": "MDEyOklzc3VlQ29tbWVudDMwNzQwOTkzMQ==", "user": {"login": "apaszke", "id": 4583066, "node_id": "MDQ6VXNlcjQ1ODMwNjY=", "avatar_url": "https://avatars3.githubusercontent.com/u/4583066?v=4", "gravatar_id": "", "url": "https://api.github.com/users/apaszke", "html_url": "https://github.com/apaszke", "followers_url": "https://api.github.com/users/apaszke/followers", "following_url": "https://api.github.com/users/apaszke/following{/other_user}", "gists_url": "https://api.github.com/users/apaszke/gists{/gist_id}", "starred_url": "https://api.github.com/users/apaszke/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/apaszke/subscriptions", "organizations_url": "https://api.github.com/users/apaszke/orgs", "repos_url": "https://api.github.com/users/apaszke/repos", "events_url": "https://api.github.com/users/apaszke/events{/privacy}", "received_events_url": "https://api.github.com/users/apaszke/received_events", "type": "User", "site_admin": false}, "created_at": "2017-06-09T14:50:12Z", "updated_at": "2017-06-09T14:50:12Z", "author_association": "MEMBER", "body_html": "<p>One way would be to add a number of prints inside the <a href=\"https://github.com/pytorch/pytorch/blob/master/torch/utils/data/dataloader.py#L29-L45\">worker loop</a>. I have no idea why do they silently exit. It's probably not an exception, because it would have been printed to stderr, so they either break out of the loop, or get killed by the OS (perhaps by a signal?)</p>", "body_text": "One way would be to add a number of prints inside the worker loop. I have no idea why do they silently exit. It's probably not an exception, because it would have been printed to stderr, so they either break out of the loop, or get killed by the OS (perhaps by a signal?)", "body": "One way would be to add a number of prints inside the [worker loop](https://github.com/pytorch/pytorch/blob/master/torch/utils/data/dataloader.py#L29-L45). I have no idea why do they silently exit. It's probably not an exception, because it would have been printed to stderr, so they either break out of the loop, or get killed by the OS (perhaps by a signal?)"}